# Generated by Django 3.1.3 on 2021-01-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLinksResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('original_link_url', models.CharField(max_length=250)),
                ('original_link_status', models.CharField(max_length=250)),
                ('history', models.CharField(max_length=250)),
                ('final_link_url', models.CharField(max_length=250)),
                ('final_link_status', models.CharField(max_length=250)),
            ],
        ),
    ]
