# Generated by Django 3.1.3 on 2021-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_my_links', '0002_checklinksresult_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklinksresult',
            name='original_link_status',
        ),
        migrations.AlterField(
            model_name='checklinksresult',
            name='check_date',
            field=models.DateField(auto_now=True),
        ),
    ]
