# Generated by Django 3.1.3 on 2021-01-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_my_links', '0003_auto_20210125_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklinksresult',
            name='upload_date',
        ),
    ]
