# Generated by Django 3.1.3 on 2021-01-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_my_links', '0004_remove_checklinksresult_upload_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckLinksResult',
        ),
    ]
